config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root :to => "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
  

app/models/book.rb
class Book < ApplicationRecord
    #Help do ActiveStorage para que os dados da imagem seja salvos na tabela storage
    has_one_attached :image
    #validação para presença de valor nos campos
    validates_presence_of :title,:author,:description,:status
    #Status definido para os livros onde publicado fica disponivel e arquivado indisponivel na pagina inicial
    enum status: [:publicado, :arquivado]
    #Validação de tamanho de caracteres
    validates_length_of :title, minimum: 4, maximum: 100, allow_blank: true
    validates_length_of :description, minimum: 10, maximum: 260, allow_blank: true
    validates_length_of :author, minimum: 5, maximum: 100, allow_blank: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Status do usuario
  enum status: [:ativo, :inativo]
  # Perfil de acesso
  enum profile: [:admin, :comum]

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  #Help do devise para autenticação do usuario na controller Admin
  before_action :authenticate_user!, :check_login_user
  #Layout para autenticação do usuario admin
  layout 'admin'

  protected

  #Verificação de perfil de usuario
  def check_login_user
    if user_signed_in?
      if current_user.inativo? || current_user.comum?
        Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
        redirect_to root_path
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/books_controller.rb
class BooksController < AdminController

    #Action para visualizar todos os livros cadastrados
    def index
      @q = Book.ransack(params[:q])
      @books = @q.result(distinct: true)
      @status = Book.statuses
    end

    #Action para criação de um novo livro
    def new
      @status = Book.statuses
      @book = Book.new 
    end

    #Action de edição do livro
    def edit
      @status = Book.statuses
      @book = Book.find(params[:id]) 
    end

    #Action de criação do livro
    def create
      @book = Book.new(book_params)
      respond_to do |format|
        if @book.save
          format.html { redirect_to books_path, success: 'Widget was successfully created.' }
        else
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end

    #Action para atualizar um livro cadastrado
    def update
      @book = Book.find(params[:id]) 
      respond_to do |format|
        if @book.update(book_params)
          format.html { redirect_to books_path, success: 'Widget was successfully created.' }
        else
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end

    #Action para mostrar mais detalhes um livro cadastrado
    def show
      @book = Book.find(params[:id]) 
    end

    #Action para excluir um livro cadastrado
    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
    end
    
    private
    def book_params
      params.require(:book).permit(:title, :description,:author,:image,:status)
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #Layout para acesso a usuarios comuns e administradores
  layout 'home'
  #Action para mostra a pagina inicial do sistema
  def index
    @books = Book.where(status: :publicado)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/edit.html.erb
<div class="container">
    <br>
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <h6>Editar Livro</h6>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <%= link_to "Voltar", books_path , class:"btn btn-outline-secondary"%>
        </div>
    </div>
    <hr>

    <div class="card">
        <div class="card-body">
            <%= form_for @book, as: :book, method: :put, html: { class: "row g-3 needs-validation" } do |form| %>

            <div class="col-md-6">
                <label for="validationCustom01" class="form-label">Titulo</label>
                <%= form.text_field :title, class: "form-control" %>
            </div>

            <div class="col-md-6">
                <label for="validationCustom01" class="form-label">Autor</label>
                <%= form.text_field :author, class: "form-control" %>
            </div>

            <div class="col-md-12">
                <label for="validationCustom01" class="form-label">Descrição</label>
                <%= form.text_area(:description,rows: 3, class: 'form-control', maxlength: 260) %>
            </div>

            <div class="col-md-6">
                <label for="formFileSm" class="form-label">Anexe uma imagem</label>
                <%= form.file_field :image,class:"form-control", id:"formFileSm" %>
            </div>

            <div class="col-md-6">
                <label for="validationCustom01" class="form-label">Status</label>
                <%= form.select :status, @status.keys.map { |w| [w.humanize, w] }, { :prompt => "Selecione o status"},  { class: "form-select" } %>
            </div>

            <div class="col-12">
                <%= form.button class: "btn btn-success" do %>
                <i class="fa fa-check-circle"> Atualizar </i>
                <% end %>
            </div>

            <% end %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="container shadow p-3 mb-5 bg-body rounded">
  <br>
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"> <%= link_to "Home", root_path %> </li>
          <li class="breadcrumb-item active" aria-current="page">Livros</li>
        </ol>
      </nav>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <div class="dropdown">
        <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
          data-bs-toggle="dropdown" aria-expanded="false">
          <%= current_user.email %>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li>
            <%= link_to "Sair", destroy_user_session_path, :method => :delete ,class:"dropdown-item"%>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <hr>

  <div class="card">
    <div class="card-body">

      <form class="row g-3">
        <%= search_form_for @q , url: books_path do |f| %>

        <div class="col-sm-6">
          <label for="staticEmail2" class="visually-hidden">Email</label>
          <%= f.search_field :author_or_title_cont, class: "form-control", placeholder: "Pesquisar por autor ou titulo"%>
        </div>

        <div class="col-sm-2">
          <%= f.select :status_eq, @status.to_a.map { |w| [w[0].humanize, w[1]] },{:include_blank => "Selecione o Status" } , { class: "form-select" } %>
        </div>

        <div class="col-sm-4">
          <%= button_tag(class:"btn btn-primary mb-3") do %>
          Filtrar
          <% end %>
          <%= link_to "Limpar", request.path , class:"btn btn-danger mb-3"%>
        </div>

        <% end %>
      </form>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Autor</th>
            <th>Titulo</th>
            <th>Status</th>
            <th class="text-center" nowrap>Ação</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td><%= book.id %></td>
            <td><%= book.author %></td>
            <td><%= book.title %></td>
            <td>
              <% if book.publicado? %>
              <span class="badge bg-primary"><%= book.status.humanize %></span>
              <% else %>
              <span class="badge bg-danger"><%= book.status.humanize %></span>
              <% end %>
            </td>
            <td class="text-center" nowrap>
              <div class="btn-group" role="group" aria-label="Basic outlined example">
                <%= link_to "Visualizar ", book_path(book.id) , class:"btn btn-outline-secondary"%>
                <%= link_to "Editar ", edit_book_path(book.id) , class:"btn btn-outline-primary"%>
                <%= link_to 'Excluir', book, :method => :delete, data: {:confirm => "Tem certeza que deseja excluir?" },class:"btn btn-outline-danger"  %>
              </div>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>

      <hr>

      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= link_to "Novo Livro", new_book_path, class: "btn btn-primary"%>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
  <br>
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <h6>Novo Livro</h6>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <%= link_to "Voltar", books_path , class:"btn btn-outline-secondary"%>
    </div>
  </div>
  <hr>

  <div class="card">
    <div class="card-body">
      <%= form_for @book, as: :book, method: :post, html: { class: "row g-3 needs-validation" } do |form| %>

      <div class="col-md-6">
        <label for="validationCustom01" class="form-label">Titulo</label>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="col-md-6">
        <label for="validationCustom01" class="form-label">Autor</label>
        <%= form.text_field :author, class: "form-control" %>
      </div>

      <div class="col-md-12">
        <label for="validationCustom01" class="form-label">Descrição</label>
        <%= form.text_area(:description,rows: 3, class: 'form-control', maxlength: 260) %>
      </div>

      <div class="col-md-6">
        <label for="formFileSm" class="form-label">Anexe uma imagem</label>
        <%= form.file_field :image,class:"form-control", id:"formFileSm" %>
      </div>

      <div class="col-md-6">
        <label for="validationCustom01" class="form-label">Status</label>
        <%= form.select :status, @status.keys.map { |w| [w.humanize, w] }, { :prompt => "Selecione o status"},  { class: "form-select" } %>
      </div>

      <div class="col-12">
        <%= form.button class: "btn btn-success" do %>
        <i class="fa fa-check-circle"> Criar </i>
        <% end %>
      </div>

      <% end %>
    </div>
  </div>

</div>

app/views/books/show.html.erb
<div class="container">
    <br>
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <h6>Visualizar Livro</h6>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <%= link_to "Voltar", books_path , class:"btn btn-outline-secondary"%>
        </div>
    </div>
    <hr>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12 text-center">
                        <%= image_tag(@book.image, height: '300', width: '300')  if @book.image.present? %>
                </div>
                <div class="col-md-12 text-center">
                    <label for="validationCustom01" class="form-label ">Descrição</label>
                    <textarea class="form-control " id="exampleFormControlTextarea1" rows="3" disabled
                        readonly> <%= @book.description %></textarea>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/_header.html.erb
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <strong>Livros</strong>
            </a>
            <%= link_to books_path , class:"navbar-brand d-flex align-items-center" do  %>
            <%= user_signed_in? ? "Sistema": "Login" %>
            <% end %>
        </div>
    </div>
</header>

app/views/home/index.html.erb
<%= render 'home/header'%>
<!-- Imagem externa  -->
<% url_external_img = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg" %>

<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Buscador de livros</h1>
            <p class="lead text-muted">Sistema simples de busca de livros e de seus autores .</p>
        </div>
    </div>
</section>

<!-- Campo de busca dos livros -->
<nav class="navbar navbar-light justify-content-center mt-4">
    <form class="form-inline">
        <div class="input-group mb-3">
            <input class="form-control form-control-lg mr-sm-2" type="search"
                placeholder="Pesquise o nome do livro ou autor" aria-label="Search" id="search"
                aria-label="Example text with button addon" aria-describedby="button-addon1">
        </div>
    </form>
</nav>

<!-- Listagem de livros -->
<div class="album py-5 bg-light">
    <div class="card-deck">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @books.each do |book| %>
                <div class="col">
                    <div class="card shadow-sm ">
                        <%= book.image.present? ? image_tag(book.image, height: '300', width: '360')  : image_tag(url_external_img, height: '300', width: '360')%>
                        <div class="card-body">
                            <h4 class="card-title"><%= book.title %></h4>
                            <div class="dropdown-divider"></div>
                            <p class="card-text"> <%= book.description %></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">Autor: <%= book.author %></small>
                            </div>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppSearchBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Home</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'home', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= yield %>
</body>

</html>